### ISSUE TITLE
Values for --driver and --provisioner options to kitchen init

### ISSUE THREAD

**Issue by adriano-di-giovanni** [test-kitchen/test-kitchen#1139]
## Description

I'm trying to initialize Test Kitchen using `kitchen init`

I want to use Vagrant, Ansible, Serverspec, Bundler.

I know Vagrant is the default driver but I want to make it explicit.
Can you confirm `--driver=kitchen-vagrant` is correct?

I can't find the value for Ansible. Both `kitchen init --provisioner=kitchen-ansible --create-gemfile` and `kitchen init --provisioner=ansible --create-gemfile` don't put the gem in `Gemfile`
I'd expect to have something `kitchen provisioner discover` but there is none.
If I run `kitchen driver discover`, I can see `kitchen-ansible` is listed but it is not a driver.

How do I specify Serverspec via command-line? Is it possible?

Thanks
## Kitchen Version

Test Kitchen version 1.13.2

**Comment by cheeseplus** [comment]
Did you install `kitchen-ansible` via `gem install`?

**Comment by adriano-di-giovanni** [comment]
I use bundler.

Here is my Gemfile

```
source "https://rubygems.org"

gem "test-kitchen"
gem "kitchen-vagrant"
gem "kitchen-ansible"
gem "serverspec"
```

**Comment by cheeseplus** [comment]
Looking at the code it seems that we _only_ use the provisioner to write the `.kitchen.yml` and only  add Gems for _drivers_ (drivers = cloud/virtualization method, provisioners = config mgmt/shell).

Moreover the provisioner name for Ansible is `ansible_playbook` according to https://github.com/neillturner/kitchen-ansible#example-kitchenyml-file

The answer at the heart of the issue is that nobody really uses the `init` subcommand that much as in, for example the Chef ecosystem, there are other tools that generate the config so most people just kind of stopped using it and as such very little development or features have been added to it.

**Comment by cheeseplus** [comment]
The correct command:
```
kitchen init --provisioner=ansible_playbook -D kitchen-vagrant kitchen-ansible --create-gemfile
```
