### ISSUE TITLE
kitchen + berkshelf don't work together with the latest versions of gems

### ISSUE THREAD

**Issue by xeron** [test-kitchen/test-kitchen#1144]
## Description

`test-kitchen` + `berkshelf` don't work together after `gem update`.

## Kitchen Version

```
Test Kitchen version 1.13.2
```

## ChefDK Version

Not using ChefDK, using `rvm` and gems.

## Ruby Version

```
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

## Platform Version

```
macOS 10.11.6
```

## Replication Case

```
gem install test-kitchen berkshelf dep_selector
gem update
gem cleanup
kitchen setup -l debug
```

## Kitchen Output

https://gist.github.com/xeron/719cbd32d9fa3f8b3ade6e862b4f32e1

```
Message: Could not load or activate Berkshelf (Unable to activate sawyer-0.7.0, because addressable-2.5.0 conflicts with addressable (< 2.5, >= 2.3.5))
```

## Kitchen Diagnose

https://gist.github.com/xeron/e973d7fd52667d0d7ce8413cff3f57ca

I'm not sure if it's an issue with `test-kitchen` or `berkshelf`. Outside of kitchen `berks` commands work so I decided to report it here.

## Workaround

`gem uninstall addressable -v=2.5.0` fixes this issue.

**Comment by coderanger** [comment]
We recommend you use the ChefDK installer to get a working environment.

**Comment by xeron** [comment]
Thank you for proposal. I don't use ChefDK for purpose and I have no issues with my environment, `gem uninstall addressable -v=2.5.0` fixes this exact issue for me.

I'm reporting this to make sure you're aware and will work on correcting dependencies. If you think this is `berkshelf` issue feel free to close and I'll report it to berkshelf. However, as I mentioned, `berkshelf` works w/o any issues outside of the `test-kitchen`.

**Comment by coderanger** [comment]
@xeron We test the set of gems that comes with each ChefDK release together to make sure the interdependencies work smoothly. Unfortunately the Berkshelf team does not have the resources to do this continually so they do not support or recommend installing it outside of gems shipped with ChefDK (which are vetted by our release folks). Installing and managing your own gems will continue to be an option, but when it doesn't work I'm afraid the best we can say is "please don't do that" at this time, barring more resources being available.

That said, I do use Berks + Test-Kitchen via bundler for all my testing (because I'm bad at coloring inside the lines). You can see the version pins I use (mostly) at https://github.com/poise/poise-boiler/blob/master/poise-boiler.gemspec. Hope that helps.

**Comment by cheeseplus** [comment]
I'm going to close this one as per the above just cause there is only so much we or the berkshelf team can do to cover theses cases.

**Comment by xeron** [comment]
This issue has been fixed in `sawyer`: https://github.com/lostisland/sawyer/pull/46
