### ISSUE TITLE
Could not load or activate Berkshelf

### ISSUE THREAD

**Issue by eyalzek** [test-kitchen/test-kitchen#1172]
```
-----> Starting Kitchen (v1.14.2)
!!!!!! The `berkshelf' gem is missing and must be installed or cannot be properly activated. Run `gem install berkshelf` or add the following to your Gemfile if you are using Bundler: `gem 'berkshelf'`.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: Could not load or activate Berkshelf (Unable to activate berkshelf-5.3.0, because thor-0.19.4 conflicts with thor (< 0.19.2, ~> 0.19))
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

This problem doesn't happen with `berkshelf v5.2.0`.

**Comment by cody-adams** [comment]
Try finding where berkshelf 5.3.0 is installed. For me this issue was caused when berkshelf was installed in my ~/.chefdk/gem/ruby/2.3.0/gems/berkshelf-5.3.0/

After a `chef gem uninstall berkshelf` and then choosing version `5.3.0` it worked for me.

I had berkshelf 5.2.0 installed in the /opt/chefdk/embedded/ path and after i removed 5.3.0 it started using this version of berkshelf.

**Comment by cheeseplus** [comment]
If you're installing your own gems, it's worth noting that upstream Thor has an issue so you probably don't want to use thor-0.19.4 https://github.com/berkshelf/berkshelf/issues/1629

**Comment by lamont-granquist** [comment]
If TK `requires` berkshelf into the same ruby process, then it should probably stop doing that and use shell_out to call berks.

**Comment by isuftin** [comment]
This happened after I installed the latest version of ChefDK 1.1.16 on MacOS 10.10

https://github.com/test-kitchen/test-kitchen/issues/1172#issuecomment-269511473 worked for me
