### ISSUE TITLE
Support for Powershell over SSH

### ISSUE THREAD

**Issue by grv87** [test-kitchen/test-kitchen#1389]
## Description
I would like to use SSH transport for Windows machines.
I couldn't make Test Kitchen work via WinRM. And, since my machines will be used via SSH anyway, I would like to use it for Test Kitchen too.

## Kitchen Version
```ruby
1.20.0
```

## Ruby Version
```ruby
ruby 2.5.0p0 (2017-12-25 revision 61468) [x64-mingw32]
```

## Platform Version
Host: Windows 7 SP1
Target: Windows Server 2016 Base

## Replication Case
In [this gist](https://gist.github.com/grv87/4716842855d8934f3434b3548e899107):
* User data file to install OpenSSH and put SSH public key to authorized keys
* .kitchen.yml
* logs

Script in user data file works, tested with AWS. PuTTy is able to connect to just launched machine, and shell is PowerShell.

## Kitchen Output
```
Preparing solo.rb
Invalid parameter in function: (null). File: (null) Line: 0
Expression: (null)
Converge failed on instance <default-Windows>.
------Exception-------
Class: Kitchen::ActionFailed
Message: SSH exited (1) for command: [$env:TEST_KITCHEN = "1"
$dirs = @("$env:TEMP\kitchen\clients", "$env:TEMP\kitchen\cookbooks", "$env:TEMP\kitchen\data", "$env:TEMP\kitchen\data_bags", "$env:TEMP\kitchen\encrypted_data_bag_secret", "$env:TEMP\kitchen\environments", "$env:TEMP\kitchen\roles")
$root_path = "$env:TEMP\kitchen"

Function Delete-AllDirs($dirs) {
  $dirs | ForEach-Object {
    if (Test-Path ($path = Unresolve-Path $_)) { Remove-Item $path -Recurse -Force }
  }
}

Function Unresolve-Path($p) {
  if ($p -eq $null) { return $null }
  else { return $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($p) }
}

Function Make-RootPath($p) {
  $p = Unresolve-Path $p
  if (-Not (Test-Path $p)) { New-Item $p -ItemType directory | Out-Null }
}

Delete-AllDirs $dirs
Make-RootPath $root_path
] 
```

Full logs see in the aforementioned gist.

**Comment by cheeseplus** [comment]
The issue right now is the `shell_type` which as per https://gist.github.com/grv87/4716842855d8934f3434b3548e899107#file-output-kitchen-diagnose-L101 is set to `powershell` as that's the default anytime the platform is named something like "windows" (case insensitive). Try setting the `shell_type: bourne` like so:

```
platforms:
  - name: Windows
    shell_type: bourne
```

**Comment by grv87** [comment]
Well, I can with PuTTy:
![openssh](https://user-images.githubusercontent.com/2035596/38675536-be6be986-3e60-11e8-83fd-b32f955ba49a.png)
But not with Test Kitchen.

See https://github.com/powershell/Win32-OpenSSH/wiki

**Comment by cheeseplus** [comment]
Again the tooling doesn't support that configuration even if it were useful and didn't have a host of side effect problems.

**Comment by grv87** [comment]
I got it.

I believe SSH is more convenient transport than WinRM, and Test Kitchen would greatly benefit having this feature.
This could be a problem with OpenSSH itself, since they consider it not production ready. But better be ready when they finally make stable release.

Could this issue stay here opened as feature request / epic?

Are there technical reasons among the `variety of reasons` why this is unsupported now?

**Comment by cheeseplus** [comment]
To be clear: we totally agree SSH is objectively superior as a transport, nobody really thinks otherwise but there is historical context that is missing.

Way long ago, the only way to use kitchen with Windows instances _was_ SSH but one had to run a third-party SSH server and use a bash shell and it was very weird but some folks made it work. Now WinRM itself got a lot better and the community general started pushing toward that as the preferred transport for Windows (especially with respect to Win 2008 all the way to present). Microsoft itself has shifted stances several times along the way but the core message here is that WinRM became the dominant and preferred transport for several products (Kitchen, Vagrant, Packer, Ansible, etc) despite it's shortcomings - it's notably slow and it's not meant as an interactive transport in the same way SSH works.

The only Windows versions that have SSH natively supported are Windows 10 and 2016 but as mentioned earlier, that official support is _barely_ there and still considered beta. On top of that there are open questions around _how_ powershell under SSH works - morevoer CMD is the default at present. So in terms of setting sane defaults and doing this across multiple versions of Windows is incredibly problematic at this time.

Talking to some of our internal Windows pros the feeling is that this is something that will be "the new normal in 5 years. MS is going to be shifting focus from the winrm transport to ssh but it is super early days."

Is this a reasonable new feature? 
Totally
Is anyone close to using this aside from MS Insiders? 
Not even close

Are there known specific technical reasons? 
Not with the absolute latest stuff - it's just that nothing has been designed to handle this case as most Windows-centric shops aren't keen to run a beta/non-MS sponsored (in the past) SSH server on their boxes. Only as of December 2017 has there even been official-beta support in non-insider versions of Windows so this very much the bleeding edge of an ecosystem notorious for it's long-tail.

**Comment by grv87** [comment]
The bleeding edge Windows 10 feature you are talking about is another implementation. From the wiki at the link I mentioned:

> On Windows 10, if you've enabled Developer Mode, you probably have another implementation of SSH installed on your machine

Win32-OpenSSH implementation is separately installed software, not a Windows feature. And is not limited to Windows 10/2016. AFAIK it's just the reincarnation of old attempts to port original OpenSSH to Windows.

**Comment by cheeseplus** [comment]
I am referring to the thing that came after that: https://poweruser.blog/enabling-the-hidden-openssh-server-in-windows-10-fall-creators-update-1709-and-why-its-great-51c9d06db8df
