### ISSUE TITLE
test-kitchen is incompatible with latest inspec

### ISSUE THREAD

**Issue by jeffb-stell** [test-kitchen/test-kitchen#1409]
## Description

The `test-kitchen` gem is incompatible with the latest `inspec` gem due to `thor` versioning

## Kitchen Version

```ruby
1.21.1
```

## Ruby Version

```ruby
2.5.1
```

## Platform Version

OS X 10.11.6

## Replication Case

Install test-kitchen with kitchen-inspec via bundler (with a Gemfile). test-kitchen will remain at `1.15.0` or similarly old version prior to `thor` being pinned in the `test-kitchen` gemspec. This is because modern `inspec` pins `thor` above `0.20.0`

If test-kitchen is not broken for newer thor, can the gem version restriction be loosened somewhat?

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by coderanger** [comment]
The problem is that Berkshelf depends on Thor 0.19 and if using a Berksfile, it has to be loadable. The correct fix is probably to transition the Berks integration to run as a subprocess but no one has had the time to do that yet.

**Comment by s-bernard** [comment]
Hi, latest berkshelf depends on Thor 0.20:
```
berkshelf was resolved to 7.0.2, which depends on
      thor (>= 0.20)
```

**Comment by s-bernard** [comment]
By the way, if thor 0.20 works for test-kitchen (which I believe is true since it is released), adding the '>= 0.20' condition while keeping the '< 0.19.2' would have prevent this issue by just forbidding the broken 0.19.2 version while letting others choose between pre or post 0.19.2.

The rule when defining a '<' condition because of a broken version should be to allow a further version as soon as a working version exists, and not have to synchronize across the ecosystem.

**Comment by cheeseplus** [comment]
We just bumped the deps on both projects and are intimately aware of the best resolution.

**Comment by tas50** [comment]
This should be good now that we've cleaned up deps
