### ISSUE TITLE
How to run a specific files tests?

### ISSUE THREAD

**Issue by nitrocode** [test-kitchen/test-kitchen#1449]
## Description

I have a directory of tests/ and there are over 50 files. If I want to add a new file `test50.rb` how do I test just that file? For the time being, I've been creating a subdirectory

    mkdir -p tests/test
    mv tests/test50.rb tests/test/

and then running `kitchen verify --test-base-path tests/test`. Is there a better way?

## Kitchen Version

```ruby
Test Kitchen version 1.22.0
```

## ChefDK Version

```ruby
Chef Development Kit Version: 3.1.0
chef-client version: 14.2.0
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.4
kitchen version: 1.22.0
inspec version: 2.1.72
```

## Ruby Version

```ruby
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin15]
```

## Platform Version

OSX 10.13.6

**Comment by coderanger** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.

**Comment by nitrocode** [comment]
@coderanger would you fine folks accept this as a feature request instead of a question?

I'd like to be able to run a specific test without having to move my test file into a separate directory and without having to modify the `.kitchen.yml` file.

Ideally

    kitchen verify --test tests/test50.rb

Relevant:
* https://stackoverflow.com/questions/51784769/running-specific-puppet-tests-using-kitchen
* https://github.com/test-kitchen/test-kitchen/issues/1445

**Comment by coderanger** [comment]
We won't be adding this as a feature, sorry. You can split up large test harnesses into multiple suites, I recommend you use that.

**Comment by nitrocode** [comment]
@coderanger what if you got a pull request from an eager developer?

**Comment by coderanger** [comment]
Still no, the correct solution is multiple suites. TK is run by a skeleton crew so we are very hesitant about any new features which add the code complexity or maintenance burden. We already have a system for this so we don't need another :)

**Comment by coderanger** [comment]
Alternatively, add this in your own Verifier plugin, but that's probably more complex than you want to deal with.
