### ISSUE TITLE
junit output support

### ISSUE THREAD

**Issue by tas50** [test-kitchen/test-kitchen#1704]
This breaks out the junit output format support from  https://github.com/test-kitchen/test-kitchen/issues/322

It would be helpful to support industry standard output formats so we can integrate better with CI systems.

**Comment by Annih** [comment]
I made something simple and "ugly" for our CI integration.
It is simple as the tests represents the different phases (create, converge, verify, etc.), and the results are boolean succeeds or not:
* when there is a convergence error you need to read the kitchen.log to find it.
* the verify results are not handled, however you can use inspec + its junit formatter

it is currently ugly, since I had to monkey patch test-kitchen from another gem. Also the XML generation is ... very manual :D

Would you be interested if I send a PR with my code integrated inside test-kitchen?
