### ISSUE TITLE
Have access to node attributes in tests

### ISSUE THREAD

**Issue by svanzoest** [test-kitchen/test-kitchen#174]
I keep finding that the tests require knowledge of the cookbook attributes to be able to test the cookbook properly. Since this is a cookbook specific test, it is easy to just not change them and assume that the cookbook defaults are the attributes that will be used and code the tests accordingly.

I do wonder if there would be a good way to provide the node attributes and ohai data to the tests, maybe via environment variables or some yaml config written out after the solo run, that would allow for testing that attribute changes actually are respected.

**Comment by kcd83** [comment]
@sethvargo you are probably the best to answer my question about integration testing with attributes (similar to http://stackoverflow.com/questions/23549804/chefspec-and-test-kitchen)...

Example: If I have a cookbook (generic webserver) that installs an application (website) based on attributes, I thought it would be good to check if the relevant log file is created (syslog configuration). But this is neither satisfied by ChefSpec (needs a real VM with application started) nor TestKitchen (cannot write a test than knows which application is installed because cannot read attributes). Have I just hit a nasty crossroad where application meets infrastructure?

For everyone's benefit you can probably clarify why this is out of scope or correct a wrong assumption I have made. Well at least I assume others will benefit otherwise I just hi-jacked this issue, sorry!

**Comment by Atalanta** [comment]
> On 16 Apr 2015, at 19:36, kcd83 <notifications@github.com> wrote:
> Example: If I have a cookbook (generic webserver) that installs an application (website) based on attributes, I thought it would be good to check if the relevant log file is created (syslog configuration). But this is neither satisfied by ChefSpec (needs a real VM with application started)
> 

Nor should it be.  This is not the purpose of ChefSpec.
> nor TestKitchen (cannot write a test than knows which application is installed because cannot read attributes)
> 

Test Kitchen can absolutely see attributes, and this is how you should test your cookbook.

S.

**Comment by kcd83** [comment]
@Atalanta this thread concludes with 
>we don't feel that providing access to the node object or its attributes is a good idea

so what are you saying?

**Comment by dtenenba** [comment]
After reading this through, I still don't understand something basic. I have the following cross-platform  (windows, unix) recipe:

```
if node['os'] == 'windows'
    path = "C:/temp"
else
    path = "/tmp"
end

directory path

template File.join(path, 'server-info.txt') do
  source 'server-info.txt.erb'
end

```

I'd like to test it in a cross-platform way, this was my naive attempt:

```
require 'spec_helper'

if node['os'] == 'windows'
    path = "C:/temp"
else
    path = "/tmp"
end

file = File.join(path, 'server-info.txt')

describe file do
  it 'exists' do
    it { should exist }
  end
end

```

... but `node` is not available in my tests.
I can't use the approach described above of reading a json file containing the node attributes, because of a chicken and egg problem: I don't know where the json file will be, in `/tmp` or `c:/temp`.

This seems like a common enough problem. Attributes don't help because they are hardcoded, whereas in my case the os is only known at runtime.
What's the solution? I'd prefer to stick with serverspec if possible.

**Comment by cheeseplus** [comment]
So there are two aprts to this
1. using node attributes in ServerSpec defeats it's very design intention as an outside in system (it is not supposed to know anything about the cfg mgmt that set it up, only to validate that settings externally)
2. The OS information is discoverable using ServerSpec's built in types:

``
os[:family]  # redHat, ubuntu, debian and so on
os[:release] # OS release version
os[:arch]    # i386 or x86_64
```
http://serverspec.org/advanced_tips.html

With point 1 made, you can push attributes into ServerSpec tests but it's a hack, and as stated above, defeats the design intention of ServerSpec (and frameworks like it) but it can be done by using the below:

http://jakshi.com/blog/2014/05/12/accessing-chef-attributes-in-serverspec-tests/

As I said, this is kind of a hack and IMO (well lots of others too) it defeats the purpose of having a blackbox test as ServerSpec is designed such that you can SSH against a node without knowing anything about it to validate tests.

**Comment by dtenenba** [comment]
Thanks. I came up with a dumb but effective way to work around this:

```
require 'spec_helper'

if File.exists? "c:/temp"
    path = "c:/temp"
elsif File.exists? "/tmp"
    path = "/tmp"
else
    raise "What OS is this?"
end

file = File.join(path, 'server-info.txt')

describe file(file) do
  it { should exist }
end

```

**Comment by cheeseplus** [comment]
The method I mentioned above where you use ServerSpec's built in types is the most ServerSpec-y way to do it but if that works for you then awesome!

**Comment by dtenenba** [comment]
I'd prefer to do things in the ServerSpec-y way. I wish all the possible values for `os[:family]` were documented so I don't have to tediously discover them on mac, windows, and ubuntu (the platforms I am testing).
For the record, those values are `darwin`, `ubuntu`, and `windows`.

**Comment by cheeseplus** [comment]
Sorry, we don't maintain serverspec and the team who writes it is Japanese so documentation takes a bit and they don't allow issues. This is related to why we created https://github.com/chef/inspec which has a kitchen driver at https://github.com/chef/kitchen-inspec. It's still relatively new but it's already replacing lots of ServerSpec testing in cookbooks.

**Comment by mwrock** [comment]
Possibly of interest here: http://www.hurryupandwait.io/blog/accessing-chef-node-attributes-from-kitchen-tests

This refers to a recipe you can append to kitchen run lists that exports all node attributes accessible to a serverspec (or other verifier) test.
