### ISSUE TITLE
Permit specifying busser plugins version and source

### ISSUE THREAD

**Issue by cl-lab-k** [test-kitchen/test-kitchen#232]
When test-kitchen installs busser plugins, it just uses the suite directory name, so busser plugins are always the latest version from rubygems.org.

It would be nice to be able to specify the busser plugin version and gem installation source.

**Comment by tas50** [comment]
At this time I'm going to close this issue out. Busser is not a priority technology for us. If someone in the community wants to bring Busser support up to date I think we'd support doing that. It's not going to be work that we take on though since our focus is InSpec and any other verifier that runs in a more direct fashion.
