### ISSUE TITLE
`kitchen converge` uses different PATH than `vagrant provision`

### ISSUE THREAD

**Issue by mlafeldt** [test-kitchen/test-kitchen#279]
I just noticed that `kitchen converge` differs from `vagrant provision` in that it doesn't provision systems via a login shell (e.g. bash -l). This means that a custom PATH set in `/etc/profile.d` is not applied and recipes that rely on that behavior do not work under test-kitchen. For example, a guard running `which` to check that some software is already installed in a custom PATH, will always return false.

Is this intended behavior? Am I missing some setting? Or am I doing it wrong in the recipe in the first place? :)

**Comment by fnichol** [comment]
After talking this through out loud, I realize I've misunderstood the intent here. Test Kitchen's SSH transport does work this way, somewhat by design as does other Chef-related tools such as `knife bootstrap`. I've had this exact issue with the rvm and rbenv cookbooks in the past which involved prepending session loading before the relevant execute resources.

How are you invoking your Chef runs on nodes in production environments? Typically these Chef runs aren't fired from a login session which would cause the cookbook code to fail.

**Comment by mlafeldt** [comment]
To be honest, I no longer care about this issue.

You're right that cookbooks probably shouldn't rely on being executed in an interactive shell session.

That being said, feel free to close this issue.

**Comment by acqant** [comment]
I'm writing a base cookbook that uses magic_shell_environment and I'm writing test cases which don't work because kitchen-verify doesn't do an interactive login.

**Comment by acqant** [comment]
I worked around it with 'bash --login -c env | grep no_proxy'  and then my test. 

Never fails..comment on something and then I work around it.
