### ISSUE TITLE
Platform detection

### ISSUE THREAD

**Issue by dpetzel** [test-kitchen/test-kitchen#325]
So I took at stab at getting the chef-solo provisioner working on a Windows guest over WinSSHD. This actually took very few changes.

In .kitchen.yml I added the following under my platform entry for my windows node:

```yaml
provisioner:
  root_path: 'c:\tmp\kitchen'
  sudo: false
```

With those changes and this diff I was able to get chef to run. However I'm wondering what a **better** way to detect that its a windows instance would be (relying on the literal string of 'windows' in the platform name is not very reliable). I'm sure there a numerous ways to detect this, but I'm wondering what the proper/intended/planned method of doing this will be?:

```diff
--- a/lib/kitchen/provisioner/chef_base.rb
+++ b/lib/kitchen/provisioner/chef_base.rb
@@ -110,7 +110,14 @@ module Kitchen
       def init_command
         dirs = %w{cookbooks data data_bags environments roles clients}.
           map { |dir| File.join(config[:root_path], dir) }.join(" ")
-        "#{sudo('rm')} -rf #{dirs} ; mkdir -p #{config[:root_path]}"
+        if instance.platform.name.downcase.include?("windows")
+          dirs.gsub!('/', '\\')
+          "for %a in (#{dirs}) do ( IF EXIST %a (rmdir /q /s %a))" +
+            " && IF NOT EXIST #{config[:root_path]} (mkdir #{config[:root_path]})"
+        else
+          "#{sudo('rm')} -rf #{dirs} ; mkdir -p #{config[:root_path]}"
+        end
+
       end
```

**Comment by tyler-ball** [comment]
We're triaging a bunch of Windows bugs.  Because this is old, a lot has changed and we have much better Windows support.  To help answer the question of `how do I detect the current platform` @fnichol added some helpers like [powershell_shell?](https://github.com/test-kitchen/test-kitchen/blob/windows-guest-support/lib/kitchen/provisioner/chef_solo.rb#L49) and [windows_os?](https://github.com/test-kitchen/test-kitchen/blob/windows-guest-support/lib/kitchen/provisioner/chef_solo.rb#L61).

I'm going to go ahead and close this because we are closing in on Windows parity.  The 1.4 release of Test Kitchen should fully support this, and you can see the latest changes right now in the windows-guest-support branch.
