### ISSUE TITLE
Using search functions.

### ISSUE THREAD

**Issue by alfredopalhares** [test-kitchen/test-kitchen#337]
Is it possible to moch search functions results?
Or at least a way to disable this code and still be able to test the rest of the code ?

```
      Net::HTTPFatalError
       -------------------
       500 "Internal Server Error"


       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/pgbarman/recipes/server.rb:58:in `from_file'


       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/pgbarman/recipes/server.rb:

        51:  
        52:  directory node["pgbarman"]["conf_dir"] do
        53:    owner node["pgbarman"]["user"]
        54:    group node["pgbarman"]["user"]
        55:    mode 00700
        56:  end
        57:  
        58>> nodes = search(:node, "name:* AND recipes:postgresql\:\:server AND recipes:pgbarman")
        59:  
        60:  nodes.each do |n|
        61:    template "#{node["pgbarman"]["conf_dir"]}/#{n["name"]}.conf" do
        62:    source "postgresql.conf.erb"
        63:    owner node["pgbarman"]["user"]
        64:    group node["pgbarman"]["user"]
        65:    mode 00644
        66:    variables({
        67:      :name => n["name"],

```

**Comment by tomjrob** [comment]
I know this is a closed ticket, but I'm searching for the exact functionality described by @bplunkert. Has any progress been made in this regard?

**Comment by rherardi** [comment]
This is currently working:

Chef Development Kit Version: 0.10.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2

.kitchen.yaml

---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  node_name: kitchen_test
  environments_path: /private/var/root/chef-repo/environments/
  roles_path: /private/var/root/chef-repo/roles/
  data_bags_path: /private/var/root/chef-repo/data_bags/

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[haproxywrapper::default]
    attributes:
        SPRINTLY_ENV: "dev"

'node'.json files can be generated with Ohai.
