### ISSUE TITLE
Option to turn off ssh forwarding x11?

### ISSUE THREAD

**Issue by docwhat** [test-kitchen/test-kitchen#338]
Is there an option I can put in the `.kitchen.yml` file to turn of SSH forwarding of X11?

I don't need it and its annoying to have X11 started up whenever I test or converge.

**Comment by smurawski** [comment]
This has more to do with the base image that the driver is spinning up rather than a test-kitchen issue.  If it were to be addressed in the test-kitchen space, it would have to be in the driver (all of which are plugins separate to this project).  Vagrant was listed the driver for this case and the repo for that is https://github.com/test-kitchen/kitchen-vagrant
