### ISSUE TITLE
Provide some way for Chef to know it's running under test

### ISSUE THREAD

**Issue by mfischer-zd** [test-kitchen/test-kitchen#458]
It would be nice if test-kitchen provided a published way for Chef to know that it's running under test-kitchen control.  This would allow us to modify its behavior in testing.  (I'll concede that this is normally undesirable behavior, but there are cases where it's useful or necessary.)

An example of a case where we need it would be access to secret data (we don't use encrypted data bags; we have our own vault).  In production, we have a method `Chef::Node.secret` that fetches the secret from the vault, and its implementation would necessarily differ in a test harness because developer environments and CI bots like Travis won't have access to the vault.  So we'd want the `secret` method to behave differently when run under test-kitchen to do something else (e.g. provide fake secret data).

Obviously we can put a `testing: true` attribute into each suite and/or provisioner definition, but that's pretty clunky and would require it be put into every cookbook's `.kitchen.yml` file.

What do you think about having test-kitchen set an environment variable like `CHEF_TESTING=1` (feel free to select a different name) before executing `chef-client`?

**Comment by fooshards** [comment]
Use case:  Many oracle products, and some other nicer better behaved products gloriously fail installations or at runtime if a host can't properly resolve its external hostname.  If it contains localhost, it fails via some hardcoded logic in their app.  This is obviously disastrous in test-kitchen context, and the solution is to take control of / insert a line in the hostfile.

This is not a desired behavior in production or managed environments.  But it is a NECESSITY, when dealing with disposable, local VM's.  I'd love a canonical way to add some compatibility to a recipe by saying: `only_if node['test_kitchen']` or something similarly succinct.

**Comment by coderanger** [comment]
I should probably state for the record that my earlier arguments were bad and I was totally wrong.

**Comment by lamont-granquist** [comment]
I would be :+1: on this.  I do think that in the wild about 80% of the time it'll be used badly when another approach would be better.  I would bet that half the people on this thread that want this feature shouldn't be using it.  But the other 20% of the use cases aren't possible without it, other than the silly implementation-dependent hacks we have now.  Another case where I firmly believe in the Right to Keep and Bear Footguns.

**Comment by coderanger** [comment]
@lamont-granquist Said far better than I could.

**Comment by charlesjohnson** [comment]
I feel equal parts validated and annoyed.

I continue to be :+1:

**Comment by martinb3** [comment]
> Another case where I firmly believe in the Right to Keep and Bear Footguns.

:+1:

**Comment by Sauraus** [comment]
Another use case, is the fact that multi-node testing in TK is not possible at present and in the case of the [https://github.com/chef-cookbooks/jenkins](jenkins) cookbook that means it is impossible to test whether a slave node will converge properly because my wrapper cookbook will at some point call the LWRP that adds the slave to a master which does not exist in a TK setup.

**Comment by CVTJNII** [comment]
I'm also in favor of this footgun.  My use case is I have a high level cookbook that sets up a machine to a production baseline for Docker.  It sets up things like log shipping and consul registration that are very important in production, but cause all kinds of headaches in test.  I strongly desire for this cookbook to function such that my users can simply depend on it and be assured that their system will meet our production specs, but also not have to worry about twiddling bits in the kitchen attributes to disable production features that need special handling under test.

I'm currently using flags that must be twiddled in test, and that's painful because it requires the settings to be distributed into the .kitchen.yml of all cookbooks that depend on this.  Beyond being a nuisance for my users it poses a big headache if I need to change any of these settings, most of which are irrelevant to the other cookbooks except for getting tests to run.  Going the other way I could set the default to off and enable it outside of kitchen, but that's painful because there really isn't a central place to enable the setting (namely because of multiple environments) and I believe the risk of having these settings disabled due to an oversight is greater than the test pain.

So, I'd like to use this setting in this cookbook, which is unique to our environment, to ensure production bits are on in production and off in tests where they're not needed.  If nothing else it will allow me to keep all the spiders in one place so that I can easily sweep them out later.

**Comment by grimm26** [comment]
FYI this would be useful for when I don't want to pull a license for something in test-kitchen.

**Comment by coderanger** [comment]
So as ^^ mentions, I think #1081 addresses this well enough to get the job done without too much bikeshedding.

**Comment by mwrock** [comment]
fixed via #1081
