### ISSUE TITLE
Run serverspec tests in 'ssh mode' instead of 'inside the machine'

### ISSUE THREAD

**Issue by michaellihs** [test-kitchen/test-kitchen#539]
Hi there,

I would like to ask, whether there is a possibility to run the serverspec tests via ssh instead of running them 'inside' the box after setting up busser etc. in the virtual machine.

There are two reasons for me, why I want to do this:

1) We are workgin with FreeBSD and ran into severe problems with the "in-the-box" solution (busser dependencies could not be installed as required).

2) My goal is to run an outside-in test approach and I think it's not a good idea to "change" the state of the converged machine but rather leave it in the state of the provisioning for running the tests.

So it would be great to know, whether there exists a solution for running serverspec tests via ssh or whether I can write kind of a plugin for testkitchen for this purpose.

Any help is appreciated!

Thanks a lot in advance,

Michael

**Comment by cheeseplus** [comment]
Check out https://github.com/chef/kitchen-inspec

InSpec is what we (as Chef) are replacing our serverspec usage with as it's a bit more flexible and has some significant architectural improvements over serverspec. I'd also be happy merge a PR but this would belong under `busser-serverspec` which is plugin (now)

Closing here but feel free to open under `busser-serverpec` or start using `kitchen-inspec`

**Comment by cl-lab-k** [comment]
hi, @michaellihs 
you can use `shell verifer` instead of `busser`, it lets serverspec run with ssh mode.

* https://github.com/test-kitchen/test-kitchen/pull/741 (it has been merged TK 1.5)
* https://rubygems.org/gems/kitchen-verifier-shell (if you use TK 1.4, install gem)

here is my `shell verifer` and `serverspec` example:
https://github.com/cl-lab-k/apache2-take/tree/shell_verifier
