### ISSUE TITLE
winrm: Use the rdp_uri instead of trying to call specific application

### ISSUE THREAD

**Issue by docwhat** [test-kitchen/test-kitchen#595]
This applies specifically to OS X, but probably applies for Windows and even Linux.

Microsoft has an [rdp_uri specification](https://technet.microsoft.com/en-us/library/dn690096.aspx) for creating a URI to open a specific remote desktop.

Currently, the OS X [`mac_login_command()`](https://github.com/test-kitchen/test-kitchen/blob/windows-guest-support/lib/kitchen/transport/winrm.rb#L153-L173) tries to find the *old* Microsoft remote desktop application.  The new one is [Microsoft Remote Desktop](https://itunes.apple.com/us/app/microsoft-remote-desktop/id715768417?mt=12).

Instead of hardcoding the application (with all the problems with knowing where it is, etc.) you should use something like `open 'rdp://full%20address=s:10.0.0.15&username=s:Administrator'` which will open either the old `Remote Desktop Connection.app` or the new `Microsoft Remote Desktop.app` which ever is installed.

This approach should work for Windows. (I'm not sure how you ask Explorer to open a URI, but it'll do the right thing)

It should also work on Linux with the `xdg-open` command.

**Comment by fnichol** [comment]
I'm hoping that the [updated implementation](https://github.com/test-kitchen/test-kitchen/blob/v1.4.0.beta.2/lib/kitchen/transport/winrm.rb#L109-L122) will cope better with application differences. Here's the `Winrm::Connection#login_command` strategy:

* Mac: make a `*.rdp` document and call `open` on it (opening your registered application)
* Windows: make a `*.rdp` document and call `mstsc` on it.
* Linux: call `rdesktop` with `-u`, `-p` and a URI set.

You can try this out by upgrading to a 1.4.0.beta.* release (or later), or using master directly. Since I hope we have this covered, I'm going to close this issue off. If I'm wrong and you're getting different behavior, or the wrong application is being opened, please reopen or file a new issue so we can make this rock solid.

Thank you! :cake:

**Comment by atomic-penguin** [comment]
Some newer distributions are switching to freerdp, instead of rdesktop.  It would be nice to have a knob.  But this is hardly a blocker since one can just symlink rdesktop to xfreerdp as a workaround, both use the same command line switches.
