### ISSUE TITLE
destroy on fails but not on succcess

### ISSUE THREAD

**Issue by hd-deman** [test-kitchen/test-kitchen#627]
`--destroy=(passing, always, never)` I really miss destroy only if test fails.
My case:
- test cookbook with docker_cli plugin
- build images from tested containers if test passed

so I can't destroy on success because I need containers for build images
but I need destroy containers if tests fails.

**Comment by cheeseplus** [comment]
Are you asking for another option for `--destroy` that destroys the instance on failure?

**Comment by jmccann** [comment]
I don't know if that is what @hd-deman is asking for ... but that is how I read it and that is partially what I want.

My use case is I do testing in a CI environment and no matter what I want it to clean up after itself.  So for me `always` should also delete on a failure as well.  Otherwise I am left with artifacts in my docker and/or openstack environment.

So for me have `--destroy=(passing, failure, always, never)` and also having `always` to always destroy ... including during a failure.

**Comment by cheeseplus** [comment]
That seems entirely reasonable and probably not too much code at all.

**Comment by hd-deman** [comment]
This is exactly what I means.
Чт, 14 апр. 2016 г. в 21:48, Seth Thomas <notifications@github.com>:

> That seems entirely reasonable and probably not too much code at all.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/test-kitchen/test-kitchen/issues/627#issuecomment-210095511>
>
-- 
Best wishes, Dmitry Tsoy.
<https://www.englishforums.com/media/p/,1982614,15011,5.htm>
