### ISSUE TITLE
require_chef_omnibus re-installs chef-client when not needed

### ISSUE THREAD

**Issue by haidangwa** [test-kitchen/test-kitchen#691]
When we run `kitchen test`, our VM installs the appropriate version of chef-client and the chef run completes successfully. We don't have Test Kitchen destroy the VM when it's done, but on subsequent runs, we will use `kitchen converge` on the same VM, it will re-install the same version of chef-client that is already installed in the VM. The expected behavior is that the `kitchen converge` should sync our cookbooks to pick up changes/fixes as we iterate fixes to the cookbooks. We also don't expect it to re-install chef-client and this unnecessarily extends the entire run by doing so.

To workaround this, we've hacked this workaround into the .kitchen.yml file:

```
provisioner:
   name: <%= provisioner %>
+  <% if ARGV[0] =~ /test/ %>
   require_chef_omnibus: <%= omnibus_version %>
+  <% end %>
```

As long as the provisioner section doesn't include the line for `require_chef_omnibus` when we run `kitchen converge`, the run will detect that the chef-client is already installed (at the right version) and skips that test.

**Comment by tyler-ball** [comment]
Hey @haidangwa - can you paste the output of your `kitchen diagnose` into a gist so we can see it?  I have a suspicion that the `require_chef_omnibus` is being set to `latest`, which is a poorly named config attribute.  `latest` means `re-install the latest chef version every time` which is what you are seeing.  If this is true, then our documentation needs updating.  If its not, there is some other bug that we will figure out.  But the `kitchen diagnose` output should help greatly!

**Comment by tyler-ball** [comment]
I'm going to tag this as a documentation error - we need to update https://docs.chef.io/config_yml_kitchen.html to be correct

**Comment by dpetzel** [comment]
This issue doesn't only happen with latest. In my case I have a hard coded version of `11.16.4` each and every time I run `kitchen converge` it keeps re-installing that version over and over (making iteration much slower than it should be). 

In my case, I don't run `kitchen test` without destroy before iteration, instead I simply run converge to get things up the first time and then keep converging. The workaround I'm using is to set the version I need once, and then change it the value of `true` while this works its proven error prone as we forget to undo that and when the next person comes along they get some old version thats pre-installed on our images.

I would expect the behavior to be as follows:
* `true` - work as it does today, and install latest if nothing is installed, otherwise noop
* `11.16.4` - install 11.16.4 if that is not the version currently installed (ie upgrade or downgrade), or if no version is installed at all. If this version is already installed do nothing
* `latest` - if no version is installed install latest, if a version is installed, check if its latest and only install if its not. If the latest version is already installed, do nothing.
