### ISSUE TITLE
Abstract chef provisioner to external gem

### ISSUE THREAD

**Issue by EslamElHusseiny** [test-kitchen/test-kitchen#754]
I guess KitchenCI needs to be more modular in provisioner section, I.e. instead of having chef installed and enabled by KithchenCI, it needs to be a separate gem like kitchen-puppet one.

What do you think ?

**Comment by rmoriz** [comment]
it's already modular and different provisioners are available, e.g. https://github.com/neillturner/kitchen-puppet and https://github.com/neillturner/kitchen-ansible

**Comment by neillturner** [comment]
it would be better if KitchenCI was like librarian and the chef provisioners were external gems to testkitchen so that could be modified separately. It has certainly helped me develop the puppet and ansible versions this way.

 I also believe in the long run test-kitchen could replace chefserver and puppetmaster and ansible tower, particularly in cloud envronments like aws and provide a more lightweight devops tooling (a bit like how tomcat took over from websphere and weblogic).  

All it really needs is a way to have multiple .kitchen.yaml files so you can specify on kitchen command and a way of storing the result of a run (probably in status files files in the .kitchen folder) and a new command kitchen status that shows the status of runs. then kitchen could be scheduled and status could be regularly displayed.....

**Comment by EslamElHusseiny** [comment]
+1
that's what I'm talking about the separation of chef stuff from test-kitchen

**Comment by smurawski** [comment]
Test-kitchen is fully modular.  There is no dependency on Chef, though you do have Chef provisioners that ship with it.  If the complaint is that there are a couple of files in the project that include chef provisioners, that's kind of a pointless argument.  I can't speak for @fnichol, but I don't see what the benefit to the project would be in removing that handful of files to another gem.

The chef provisioners are written as plugins, just like any additional provisioner, driver, or verifier.  Case in point, using the Hyper-V driver, DSC provisioner and Pester verifier, you could stand up a system under test with no ruby on it at all and things will just work.

**Comment by neillturner** [comment]
My suggestions aren't complaints. Test kitchen is great. I'm thinking of the future and where you take the product. I am a fan of a more lightweight form of devops which test kitchen could fulfil whether it has the chef code built in or as plugins. Ofcourse chef puppet and ansible want to sell their heavyweight server enterprise products so they probably only want to keep test kitchen for "testing"

**Comment by smurawski** [comment]
So @EslamElHusseiny and @neillturner, I'm coming around to your way of thinking on pulling the chef provisioners out to their own gem.

**Comment by cheeseplus** [comment]
The new wing of maintainers are all for this separation. +1

**Comment by tas50** [comment]
Had we built this in 2021 I think we would have made chef a plugin, but at this point it really just makes things more complex and more difficult to test / ship / maintain. I'm not seeing a particular win we get out of this other than code correctness, which on its own is not a reason to ship a major change like this. I'm going to close this out unless someone can come up with a really compelling reason to move forward with this.
