### ISSUE TITLE
When state is printed to logs it prints passwords

### ISSUE THREAD

**Issue by zl4bv** [test-kitchen/test-kitchen#759]
Recently kitchen-ec2 added a feature to retrieve a Windows password from the EC2 get_windows_password API. It then stores the password in the state file. Unfortunately this means that when the state file is logged it also writes the password to the log.

e.g. (values were only masked when pasting here)

```
       Finished creating <default-windows-2012r2> (0m0.00s).
-----> Converging <default-windows-2012r2>...
       [Dummy] Converge on instance=#<Kitchen::Instance:0x3b95f68> with state={:username=>"administrator", :server_id=>"
i-xxxxxxxx", :hostname=>"xxxxxxxx", :password=>"xxxxxxxx", :last_action=>"create"}
       Finished converging <default-windows-2012r2> (0m0.00s).
```

Would it be possible to detect sensitive values in the state file and mask them when printing to logs?

**Comment by cheeseplus** [comment]
Not sure if it is but it's something we can look into - curious if this is only related to the kitchen-ec2 driver.

**Comment by smurawski** [comment]
@cheeseplus no, this is default behavior for how diagnose behaves.  Ideally, since the intention of the test-kitchen framework is to bring up, converge, test, and destroy instances, the password isn't a big deal.  

We could look at hiding the password output in the log messages, but being able to retrieve it via "diagnose" is a critical feature for troubleshooting, as it allows you to see what is being used by the transport to connect.  When troubleshooting drivers that use a different means to validate the server being up (methods other than transport), this can be key to determining what is failing when kitchen tries to talk to an instance.
