### ISSUE TITLE
Windows kitchen-tests should run in an Elevated session under System account

### ISSUE THREAD

**Issue by Annih** [test-kitchen/test-kitchen#876]
Hello,

It could be very useful that test-kitchen tries to converge within an elevated session and it would be even better if it could do this as `SYSTEM`.
One of the solution is to use schedule task (like https://github.com/WinRb/winrm-elevated); I really like this solution because it would fix so many "Access denied" issues.
What do you think?

Maybe it's already in your roadmap,but I think that having an issue could help to track the need and dev of this new feature.

cc: @aboten

**Comment by carpnick** [comment]
FYI - @mwrock, @smurawski, @sneal

I think this should be pushed even lower out of kitchen.  I believe @mwrock has on his roadmap to merge [winrm-fs and winrm-transport](https://github.com/test-kitchen/winrm-transport/issues/16),  To go one step further I would say the new merged gem, or existing one, should include the winrm-elevated as the default way to run any command.

Then the merged gem should be used by kitchen and knife-windows.

**Comment by icberg7** [comment]
Based on what I posted in #868, there are some things that will never work over WinRM, even as the system user. For more information, see: https://msdn.microsoft.com/en-us/library/windows/desktop/aa387288(v=vs.85).aspx

**Comment by carpnick** [comment]
@icberg7 
That is why the the winrm-elevated gem created a scheduled tasks, executes outside of the winrm context, and then would delete the scheduled task.

**Comment by smurawski** [comment]
I agree @carpnick this should be pushed out of test-kitchen and into the an abstracted transport.  There is a non-trivial bit of overhead to running everything through scheduled tasks in a way that you can marshal the output back to kitchen run.

That said, for the current chef-zero use case, there is the [chef-zero-scheduled-task provisioner](https://rubygems.org/gems/chef-zero-scheduled-task) which wraps the chef-zero provisioner call in a scheduled task and streams back the output.  This capability should be more generally available, but if chef-zero is your provisioner of choice then this may help.

Also, for things like the DSC provisioner, the scheduled task stuff would be overkill since DSC runs in it's own hosted process, outside of the WinRS session that invoked it, so not everything needs that level of complexity attached.

**Comment by mwrock** [comment]
Agree with @carpnick and @smurawski that the core logic for this should be downstream with a config option in test-kitchen available if one wishes not to be elevated.

**Comment by Annih** [comment]
Thanks @smurawski for this gem! I'll give it a try next week, I'm sure it'll be sufficient for my test-kitchen cases.
However I agree with all of you that it'ld be cleaner to have it downstream; it'll allow us to use the them logic for all other chef provisioning/bootstraping processes.

**Comment by styk-tv** [comment]
Thanks @smurawski @mwrock 

Is there any special trick to running chef-zero-scheduled-task elevated? Kitchen provisioner updated but it seems running standard batch. Using default transport credentials (no ST creds). userX is in Administrators group UAC is disabled. Win7, Wmf4, 64bit.

**Comment by Annih** [comment]
Normally the latest version of the provisioner run the task with `Highest Privilege`

**Comment by carpnick** [comment]
So there is one caveat with the scheduled task gem.  It only works on the chef-client execution.  It is important to know this, because we are using WMF3 which has a bug in not honoring memory settings.  So when chef-client is installed, it is via the winrm context.  So if you have any winrm blockers there, the scheduled task is just out of reach.

We worked around this, until our images go up to >=WMF4 by installing chef-client via userdata.  Then kitchen detects chef is already installed, and skips the install step.

**Comment by mwrock** [comment]
For @styk-tv 's case, I'm pretty sure he is concerned about the execution of a `batch` resource so that would definitely be happening in the chef run. As @Annih notes, the task runs with highest privilege. One way to definitively tell if you are running elevated or not from inside a shell is to run this powershell:
```
    $identity  = [System.Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object System.Security.Principal.WindowsPrincipal( $identity )
    return $principal.IsInRole( [System.Security.Principal.WindowsBuiltInRole]::Administrator )
```
It will return `$true` if you are elevated. Might try playing with something like that to troubleshoot. Could also be that your user is not the user you think it is and you could use a similar script to spit out the username.

**Comment by smurawski** [comment]
@Annih This is now supported via the transport as of v1.8.0 with
```
transport:
  name: winrm
  elevated: true
  elevated_username: System
  elevated_password: null
```

**Comment by Annih** [comment]
Yes @smurawski and @mwrock  thanks for your hard work, this is an amazing feature :)

**Comment by icberg7** [comment]
So does this mean that the chef_zero_scheduled_task provisioner is no longer necessary?

**Comment by icberg7** [comment]
Oh, I just saw https://github.com/smurawski/chef-zero-scheduled-task/commit/0001a72b3646fe3c0194ae1b05685abffd93d81d. Sweet.

**Comment by smurawski** [comment]
@icberg7 yep - it is no longer required once you are on test-kitchen 1.8.0 and newer.

**Comment by TerrapinStation** [comment]
@smurawski im late to the party here, but thanks so much for adding this. this feature has helped a lot with testing/installing tableau with test-kitchen
