### ISSUE TITLE
Chef Zero should be the default provisioner with init

### ISSUE THREAD

**Issue by tas50** [test-kitchen/test-kitchen#889]
New users shouldn't be pointed towards chef-solo.  They should get an default config with chef-zero.

**Comment by mwrock** [comment]
:+1:

**Comment by smurawski** [comment]
I'd disagree.  I think the default provisioner from init should be the shell provisioner.  

From a Chef perspective, Chef generate cookbook will drop the right thing in the .kitchen.yml, but there are several other CM tools using kitchen more and more these days.  I'm coming around to the idea of making the chef provisioners as separate gem (https://github.com/test-kitchen/test-kitchen/issues/754), since that would allow us to iterate on those faster than the kitchen ship-cycle.

If we don't go that route, I'd agree that solo should not be the default.

**Comment by mwrock** [comment]
Yeah I agree with @smurawski. While I thing chef-solo is definitely a bad default, striving to be CM agnostic is the best course for test-kitchen.

**Comment by cheeseplus** [comment]
Closing this for now as it seems if we're treating the shell provisioner for the most agnostic approach and we're definitely taking the approach of divorcing chef from TK. I've opened a new issue for this here - https://github.com/test-kitchen/test-kitchen/issues/913
