### ISSUE TITLE
Intermittent key not found: "src_md5" failures on windows nodes

### ISSUE THREAD

**Issue by mwrock** [test-kitchen/test-kitchen#926]
v1.5.0 added winrm-s to permit negotiate authentication when converging FROM windows TO windows. This monkey patches winrm and it has a bug when command output is long enough to span multiple SOAP responses. the winrm-s monkey patch throws out all but the last response. Most commands will result in a single response so this is usually not a problem.

Rather than fixing winrm-s, we should merge #902 which eliminates that gem altogether.

**Comment by cheeseplus** [comment]
We've merged this :shipit:

**Comment by stuartpreston** [comment]
I have to admit I am now completely lost with changes to winrm-transport, winrm-s, winrm, rubyntlm
I updated to the latest ChefDK 0.11.2 and expected things to be a bit more stable but after a day working on this I'm totally lost.

I'm working with a customer just trying to do "bare metal" WinRM in a corporate/domain environment. I've hit a lot of dead ends in the process:

- SSH driver in 1.5.0 is a legacy driver so doesn't support Inspec (looks like a fix is in the works - I started working on my own driver that inherits from Kitchen::Base instead)
- sspinegotiate option "randomly" generates key not found: "src_md5" failures (I can't work out what the fix is supposed to be here after an hour of browsing Github issues and gem updating)
- Kitchen-Inspec doesn't know what to do with 'sspinegotiate' and attempts to use defaults anyway (if you specify a username and password, WinRM driver tries to use them instead of negotiating and you get an authentication failure)
- Some weird utf16-le conversion issues during verify (https://github.com/chef/kitchen-inspec/issues/57#issuecomment-190644688) 
- Berksfile not picked up unless running kitchen from a cookbooks folder (probably I'm doing something wrong - my kitchen.yml is in the root of my repo rather than a specific cookbook).
- Test Kitchen 1.6.0 seems to be released but updating the gem obviously doesn't update the binstub

```
C:\Users\stp39>chef -v
Chef Development Kit Version: 0.11.2
chef-client version: 12.7.2
berks version: 4.2.0
kitchen version: 1.5.0
```

I think the biggest issue I have is converging with the src_md5 issue as it blocks the ability to converge for me. Is there a magic combination of gems and versions that work together?

@smurawski @mwrock

**Comment by stuartpreston** [comment]
FWIW

```
C:\Users\stp39\bss>chef gem list --local winrm

*** LOCAL GEMS ***

winrm (1.7.2, 1.7.0)
winrm-fs (0.3.1)
winrm-s (0.3.6, 0.3.5, 0.3.4)
winrm-transport (1.0.3)
```

**Comment by smurawski** [comment]
chef gem winrm-s --prerelease
Or test-kitchen 1.6 is fully over to rubyntlm and off of winrm-s.

**Comment by stuartpreston** [comment]
@smurawski Thank you!
