### ISSUE TITLE
WinRM: dna.json is not updated on target machine during kitchen converge unless deleted

### ISSUE THREAD

**Issue by stuartpreston** [test-kitchen/test-kitchen#957]
During testing on a bare metal Windows platform, we noticed that a change in the run_list doesn't result in a change to the dna.json on the target machine during a converge.

**2nd converge:**

```
D      Creating local sandbox in C:/Users/stp39/AppData/Local/Temp/bss-windows20
08-sandbox-20160301-7596-4atgzn
       Preparing dna.json
D      Creating dna.json from {:run_list=>["recipe[bss::messenger_sysprep_should
_be_broken]"]}
```

```
[...]
D      [FileTransporter] File $env:TEMP\kitchen\dna.json is up to date, skipping
```

Whilst I know the typical use case is with a fresh machine, and probably not changing a run_list per converge this is something that I think should be working, no?

**Comment by stuartpreston** [comment]
```C:\Users\stp39\bss>chef gem list --local winrm

*** LOCAL GEMS ***

winrm (1.7.2, 1.7.0)
winrm-fs (0.3.1)
winrm-s (0.3.7.dev, 0.3.6, 0.3.5, 0.3.4)
winrm-transport (1.0.3)
```

**Comment by mwrock** [comment]
I've seen people run into this too but never dug in. Are you seeing this on 1.5 or 1.6?

**Comment by stuartpreston** [comment]
This is still with 1.5 (for the moment). I'm not sure of the procedure to update a ChefDK binstub to 1.6 after downloading the gem...?

**Comment by mwrock** [comment]
yuck. I'll be running through this tonight to figure out what's going on.

**Comment by mwrock** [comment]
Here is what did starting from a chefdk version of 0.10.0:

1. `cup chefdk` # updated chefdk to 0.11.2 using chocolatey which is the equivilent of simply running the chefdk installer with all default settings
2. Ran `kitchen converge`

This resulted in the error: `No live threads left. Deadlock? (fatal)`. I actually tried the above sequence on two separate machines with the same resulting error. After googling, I discovered most got around this by destroying their local gem repository. I deleted `c:\users\matt\appdata\local\chefdk` and that fixed things. I'm sure this could be tracked down to some single gem but no one seems to know which and there are alot in my case.

After getting past that I started getting the `[key not found: "src_md5"]` errors that many experience on windows converges with 1.5.0. So I updated to TK 1.6.0 with:
```
chef gem install appbundle-updater
appbundle-updater chefdk test-kitchen v1.6.0
```
Thanks @thommay for tipping me off to the `appbundle-updater` gem. It worked great t oupdate my chefdk Test-Kitchen to 1.6.0.

Now `kitchen converge succeeded`

I changed the runlist and unfortunately was unable to reproduce @stuartpreston's issue. I reverted to 1.5.0 and was still unable to reproduce. I do know for sure I have seen this in the past. Perhaps it is driver related, I'm using kitchen-vagrant and I believe I saw it previously with kitchen-vsphere.

1.5.0 and 1.6.0 do have some implementation differences with regards to file uplads to the test instances so it is possible this is fixed in 1.6.0 but I'm not certain.

**Comment by stuartpreston** [comment]
Thanks Matt,

In my case I started with 0.11.2 on a clean machine. 

I'll give the appbundle-updater a go tomorrow and see if that changes any other dependencies. 

Regarding the driver I am simply using the ssh driver from test-kitchen itself and specifying winrm as the transport. I am also in a domain environment. Will do some more digging later this week when I'm back with the customer.

**Comment by stuartpreston** [comment]
Back on customer site, I got further with this, using Test Kitchen 0.6.0 (via 0.11.2 ChefDK, appbundle-updater and removing winrm-s gem) and after some debugging, there was a nested exception that was being swallowed:

If you do not specify a value for username and password (as originally worked with the :sspinegotiate transport option) then you end up here:

https://github.com/WinRb/WinRM/blob/master/lib/winrm/http/transport.rb#L146-L151

I didn't see this until I changed the following line:

https://github.com/WinRb/WinRM/blob/master/lib/winrm/winrm_service.rb#L54 to 

```
raise e
```

.split was being called against a nil user. Net net, right now you must specify a valid username and password to do negotiate auth, I believe?

I guess I'm unblocked for now, but in a domain environment having to put creds in my .kitchen.local.yml file is sub-optimal...

And I still have the issue with the dna.json not getting overwritten when it gets changed...

**Comment by mwrock** [comment]
Thanks for this info. This uncovers the loss of a feature that we introduces with 1.5.0 and really did not know we had.

`SSPINegotiate` did not require credentials unlike rubyntlm. `SSPINegotiate` defaults to the `ENV['username']`, `ENV['userdomain']` and calls native win32 `AcquireCredentialsHandle` to get a handle. From what I can surmise, when no creds are given, this will retrieve a handle for the currently logged on user. Prior to just about a month ago, the only consumer of wintm-s was knife-windows and it defaulted to `Administrator` if no user was given and prompted for a password if none was set. So when Test-Kitchen started using it in 1.5.0, we "stumbled" on this feature of using the current logon (only on a windows host) and regrettably now lose that feature.

There are a couple things we can do moving forward:

1. Short-Term: Fix the error handling so that missing credentials does not raise the `Invalid Transport` error but smething else more actionable.
2. Longer term: Add support for native win32 apis on windows hosts similar to winrm-s and use those instead of rubyntlm on windows.

I really do not think reintroducing winrm-s is a good solution. It simply monkey patches the winrm and httpclient gems and we have had lots of issues where it broke downstream gems. The better answer is to add the features in WinRM. It so happens I am a maintainer but dont have cycles to focus on this in the next few weeks.

**Comment by stuartpreston** [comment]
Thanks, I agree. I'm unblocked anyway for now. Appreciate the help.

If anyone else finds this and wants to do bare metal Winrm without Vagrant (like I did) then here's my .kitchen.yml which hijacks the built in proxy driver:

```
---
driver:
  name: proxy
  reset_command: $f="$env:TEMP\kitchen\dna.json";if (Test-Path $f){ Remove-Item $f }
  port: 5985

provisioner:
  name: chef_zero

verifier:
  name: inspec
  
transport:
  name: winrm

platforms:
  - name: win2008r2
      
suites:
  - name: default
    run_list:
      - recipe[mycookbook::myrecipe]
    attributes:
```

.kitchen.local.yml
```
---
driver:
  host: <FQDN OF MACHINE>
  username: <%= ENV['USERNAME'] %>
  password: <USER PASSWORD>
```

This is working with ChefDK 0.11.2 plus Test Kitchen 1.6.0 (updated via ```chef exec appbundle-updater```) plus the removal of ```winrm-s``` gem.
