### ISSUE TITLE
Chef client fails to install on Windows because Omnitruck API isn't providing md5 hash

### ISSUE THREAD

**Issue by FreakyDug** [test-kitchen/test-kitchen#982]
## Description

When I try to run tests on Windows VMs I get the following error:

```
$$$$$$ MD5 for C:\Users\vagrant\AppData\Local\Temp\chef-true.msi
$$$$$$ 458177d3b21888c17fd79660781d06eb does not match
$$$$$$ At line:46 char:10
$$$$$$ +   else { throw "MD5 for $dst $dmd5 does not match $md5" }
$$$$$$ +          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$$$$$$     + CategoryInfo          : OperationStopped: (MD5 for C:\User...does not ma
$$$$$$    tch :String) [], RuntimeException
$$$$$$     + FullyQualifiedErrorId : MD5 for C:\Users\vagrant\AppData\Local\Temp\chef
$$$$$$    -true.msi 458177d3b21888c17fd79660781d06eb does not match
```

Upon investigation it appears that the md5 computed from the downloaded file is being compared to an empty string. The [Omnitruck API metadata URL](https://www.chef.io/chef/metadata?p=windows&pv=2012&m=x86_64&v=12) being used doesn't return an md5 hash (just sha1 and sha256). Google's [cached version of the page](http://webcache.googleusercontent.com/search?q=cache:w0BbQCOTgRUJ:www.chef.io/chef/metadata%3Fp%3Dwindows%26pv%3D2012%26m%3Dx86_64%26v%3D12+&cd=1&hl=en&ct=clnk&gl=uk) shows it had an md5 hash on March 13.

I have not been able to find any information about the API changing and the documentation still claims it provides an md5 hash.

## Kitchen Version

```ruby
Test Kitchen version 1.4.0 
```

## ChefDK Version

```ruby
Chef Development Kit Version: 0.10.0
```

## Platform Version

Host OS: Windows 7
Guest OS: Windows Server 2012 R2

## Replication Case

I am seeing this error with all of my Windows test cases.

**Comment by christianclarke** [comment]
Confirmed.  We are seeing the exact same problem.

**Comment by schisamo** [comment]
We did make some recent updates to Omnitruck internally to begin pulling packages from packages.chef.io which only supports `SHA1` and `SHA256` checksums. `install.ps1` should be performing a `SHA256` validation when the `MD5` is not present, I wonder if there is a bug in that logic:
https://github.com/chef/mixlib-install/blob/b2495ce9db896ce8c9c0444282e67da9d5a62a7b/lib/mixlib/install/generator/powershell/scripts/helpers.ps1#L63-L76

Regardless we should be able to get a fix out to Omnitruck which will make this go away.

**Comment by FreakyDug** [comment]
The error I'm getting is in this kitchen powershell script which only looks for md5: https://github.com/test-kitchen/test-kitchen/blob/master/support/chef_base_install_command.ps1

**Comment by christianclarke** [comment]
Here is a snippet from my TestKitchen converge.
`
D      [WinRM] plaintext::http://127.0.0.1:5985/wsman<{:disable_sspi=>true, :basic_auth_only=>true, :user=>"vagrant", :pass=>"vagrant"}> (
$chef_metadata_url = "https://www.chef.io/chef/metadata?p=windows&m=x86_64&pv=2008r2&v=11.18.12"
$chef_omnibus_root = "$env:systemdrive\opscode\chef"
$msi = "$env:TEMP\chef-11.18.12.msi"
$pretty_version = "11.18.12"
$version = "11.18.12"

Function Check-UpdateChef($root, $version) {
  if (-Not (Test-Path $root)) { return $true }
  elseif ("$version" -eq "true") { return $false }
  elseif ("$version" -eq "latest") { return $true }
  Try { $chef_version = Get-Content $root\version-manifest.txt | select-object -1}
  Catch {
    Try { $chef_version = (& $root\bin\chef-solo.bat -v).split(" ", 2)[1] }
    Catch { $chef_version = "" }
  }

  if ($chef_version.StartsWith($version)) { return $false }
  else { return $true }
}

Function Get-ChefMetadata($url) {
  Try { $response = ($c = Make-WebClient).DownloadString($url) }
  Finally { if ($c -ne $null) { $c.Dispose() } }

  $md = ConvertFrom-StringData $response.Replace("`t", "=")
  return @($md.url, $md.md5)
}

Function Get-MD5Sum($src) {
  Try {
    $c = New-Object -TypeName System.Security.Cryptography.MD5CryptoServiceProvider
    $bytes = $c.ComputeHash(($in = (Get-Item $src).OpenRead()))
    return ([System.BitConverter]::ToString($bytes)).Replace("-", "").ToLower()
  } Finally { if (($c -ne $null) -and ($c.GetType().GetMethod("Dispose") -ne $null)) { $c.Dispose() }; if ($in -ne $null) { $in.Dispose() } }
}

Function Download-Chef($md_url, $dst) {
  $url, $md5 = Get-ChefMetadata $md_url

  Try {
    Log "Downloading package from $url"
    ($c = Make-WebClient).DownloadFile($url, $dst)
    Log "Download complete."
  } Finally { if ($c -ne $null) { $c.Dispose() } }

  if (($dmd5 = Get-MD5Sum $dst) -eq $md5) { Log "Successfully verified $dst" }
  else { throw "MD5 for $dst $dmd5 does not match $md5" }
}

Function Install-Chef($msi) {
  Log "Installing Chef Omnibus package $msi"
  $p = Start-Process -FilePath "msiexec.exe" -ArgumentList "/qn /i $msi" -Passthru -Wait

  if ($p.ExitCode -ne 0) { throw "msiexec was not successful. Received exit code $($p.ExitCode)" }

  Remove-Item $msi -Force
  Log "Installation complete"
}

Function Log($m) { Write-Host "       $m`n" }

Function Make-WebClient {
  $proxy = New-Object -TypeName System.Net.WebProxy
  $proxy.Address = $env:http_proxy
  $client = New-Object -TypeName System.Net.WebClient
  $client.Proxy = $proxy
  return $client
}

Function Unresolve-Path($p) {
  if ($p -eq $null) { return $null }
  else { return $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($p) }
}

$chef_omnibus_root = Unresolve-Path $chef_omnibus_root
$msi = Unresolve-Path $msi

if (Check-UpdateChef $chef_omnibus_root $version) {
  Write-Host "-----> Installing Chef Omnibus ($pretty_version)`n"
  Download-Chef "$chef_metadata_url" $msi
  Install-Chef $msi
} else {
  Write-Host "-----> Chef Omnibus installation detected ($pretty_version)`n"
}
)
D      [WinRM] opening remote shell on plaintext::http://127.0.0.1:5985/wsman<{:disable_sspi=>true, :basic_auth_only=>true, :user=>"vagrant", :pass=>"vagrant"}>
D      [WinRM] remote shell C116E251-E264-4CE5-8482-3326B11C7674 is open on plaintext::http://127.0.0.1:5985/wsman<{:disable_sspi=>true, :basic_auth_only=>true, :user=>"vagrant", :pass=>"vagrant"}>
-----> Installing Chef Omnibus (11.18.12)
       Downloading package from
       Successfully verified C:\Users\vagrant\AppData\Local\Temp\chef-11.18.12.msi

       Installing Chef Omnibus package C:\Users\vagrant\AppData\Local\Temp\chef-11.18.12.msi
$$$$$$ Exception calling "DownloadString" with "1" argument(s): "The remote name
$$$$$$ could not be resolved: 'www.chef.io'"
$$$$$$ At line:23 char:22
$$$$$$ +   Try { $response = ($c = Make-WebClient).DownloadString($url) }
$$$$$$ +                      ~~~~~~~~~~~~~~~~~~~
$$$$$$     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
$$$$$$     + FullyQualifiedErrorId : WebException
$$$$$$
$$$$$$ You cannot call a method on a null-valued expression.
$$$$$$ At line:26 char:3
$$$$$$ +   $md = ConvertFrom-StringData $response.Replace("`t", "=")
$$$$$$ +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$$$$$$     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
$$$$$$     + FullyQualifiedErrorId : InvokeMethodOnNull
$$$$$$
$$$$$$ Exception calling "DownloadFile" with "2" argument(s): "Value cannot be null.
$$$$$$ Parameter name: address"
$$$$$$ At line:43 char:6
$$$$$$ +     ($c = Make-WebClient).DownloadFile($url, $dst)
$$$$$$ +      ~~~~~~~~~~~~~~~~~~~
$$$$$$     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
$$$$$$     + FullyQualifiedErrorId : ArgumentNullException
$$$$$$
$$$$$$ Get-Item : Cannot find path
$$$$$$ 'C:\Users\vagrant\AppData\Local\Temp\chef-11.18.12.msi' because it does not
$$$$$$ exist.
$$$$$$ At line:33 char:37
$$$$$$ +     $bytes = $c.ComputeHash(($in = (Get-Item $src).OpenRead()))
$$$$$$ +                                     ~~~~~~~~~~~~~
$$$$$$     + CategoryInfo          : ObjectNotFound: (C:\Users\vagran...ef-11.18.12.m
$$$$$$    si:String) [Get-Item], ItemNotFoundException
$$$$$$     + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetIt
$$$$$$    emCommand
$$$$$$
$$$$$$ You cannot call a method on a null-valued expression.
$$$$$$ At line:33 char:30
$$$$$$ +     $bytes = $c.ComputeHash(($in = (Get-Item $src).OpenRead()))
$$$$$$ +                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$$$$$$     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
$$$$$$     + FullyQualifiedErrorId : InvokeMethodOnNull
$$$$$$
$$$$$$ msiexec was not successful. Received exit code 1619
$$$$$$ At line:55 char:28
$$$$$$ +   if ($p.ExitCode -ne 0) { throw "msiexec was not successful. Received exit
$$$$$$ code ...
$$$$$$ +
$$$$$$ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$$$$$$     + CategoryInfo          : OperationStopped: (msiexec was not... exit code
$$$$$$    1619:String) [], RuntimeException
$$$$$$     + FullyQualifiedErrorId : msiexec was not successful. Received exit code 1
$$$$$$    619
D      Cleaning up local sandbox in C:/Users/CHRIST~1.CLA/AppData/Local/Temp/sgagent-Windows2012-sandbox-20160331-69120-qcjr81
>>>>>> Converge failed on instance <sgagent-Windows2012>.
>>>>>> Please see .kitchen/logs/sgagent-Windows2012.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: WinRM exited (1) for command: [
$chef_metadata_url = "https://www.chef.io/chef/metadata?p=windows&m=x86_64&pv=2008r2&v=11.18.12"
$chef_omnibus_root = "$env:systemdrive\opscode\chef"
$msi = "$env:TEMP\chef-11.18.12.msi"
$pretty_version = "11.18.12"
$version = "11.18.12"

Function Check-UpdateChef($root, $version) {
  if (-Not (Test-Path $root)) { return $true }
  elseif ("$version" -eq "true") { return $false }
  elseif ("$version" -eq "latest") { return $true }
  Try { $chef_version = Get-Content $root\version-manifest.txt | select-object -1}
  Catch {
    Try { $chef_version = (& $root\bin\chef-solo.bat -v).split(" ", 2)[1] }
    Catch { $chef_version = "" }
  }

  if ($chef_version.StartsWith($version)) { return $false }
  else { return $true }
}

Function Get-ChefMetadata($url) {
  Try { $response = ($c = Make-WebClient).DownloadString($url) }
  Finally { if ($c -ne $null) { $c.Dispose() } }

  $md = ConvertFrom-StringData $response.Replace("`t", "=")
  return @($md.url, $md.md5)
}

Function Get-MD5Sum($src) {
  Try {
    $c = New-Object -TypeName System.Security.Cryptography.MD5CryptoServiceProvider
    $bytes = $c.ComputeHash(($in = (Get-Item $src).OpenRead()))
    return ([System.BitConverter]::ToString($bytes)).Replace("-", "").ToLower()
  } Finally { if (($c -ne $null) -and ($c.GetType().GetMethod("Dispose") -ne $null)) { $c.Dispose() }; if ($in -ne $null) { $in.Dispose() } }
}

Function Download-Chef($md_url, $dst) {
  $url, $md5 = Get-ChefMetadata $md_url

  Try {
    Log "Downloading package from $url"
    ($c = Make-WebClient).DownloadFile($url, $dst)
    Log "Download complete."
  } Finally { if ($c -ne $null) { $c.Dispose() } }

  if (($dmd5 = Get-MD5Sum $dst) -eq $md5) { Log "Successfully verified $dst" }
  else { throw "MD5 for $dst $dmd5 does not match $md5" }
}

Function Install-Chef($msi) {
  Log "Installing Chef Omnibus package $msi"
  $p = Start-Process -FilePath "msiexec.exe" -ArgumentList "/qn /i $msi" -Passthru -Wait

  if ($p.ExitCode -ne 0) { throw "msiexec was not successful. Received exit code $($p.ExitCode)" }

  Remove-Item $msi -Force
  Log "Installation complete"
}

Function Log($m) { Write-Host "       $m`n" }

Function Make-WebClient {
  $proxy = New-Object -TypeName System.Net.WebProxy
  $proxy.Address = $env:http_proxy
  $client = New-Object -TypeName System.Net.WebClient
  $client.Proxy = $proxy
  return $client
}

Function Unresolve-Path($p) {
  if ($p -eq $null) { return $null }
  else { return $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($p) }
}

$chef_omnibus_root = Unresolve-Path $chef_omnibus_root
$msi = Unresolve-Path $msi

if (Check-UpdateChef $chef_omnibus_root $version) {
  Write-Host "-----> Installing Chef Omnibus ($pretty_version)`n"
  Download-Chef "$chef_metadata_url" $msi
  Install-Chef $msi
} else {
  Write-Host "-----> Chef Omnibus installation detected ($pretty_version)`n"
}
]
>>>>>> ----------------------
D      Converge failed on instance <sgagent-Windows2012>.
D      ------Exception-------
D      Class: Kitchen::InstanceFailure
D      Message: Converge failed on instance <sgagent-Windows2012>.  Please see .kitchen/logs/sgagent-Windows2012.log for more details
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: WinRM exited (1) for command: [
$chef_metadata_url = "https://www.chef.io/chef/metadata?p=windows&m=x86_64&pv=2008r2&v=11.18.12"
$chef_omnibus_root = "$env:systemdrive\opscode\chef"
$msi = "$env:TEMP\chef-11.18.12.msi"
$pretty_version = "11.18.12"
$version = "11.18.12"

Function Check-UpdateChef($root, $version) {
  if (-Not (Test-Path $root)) { return $true }
  elseif ("$version" -eq "true") { return $false }
  elseif ("$version" -eq "latest") { return $true }
  Try { $chef_version = Get-Content $root\version-manifest.txt | select-object -1}
  Catch {
    Try { $chef_version = (& $root\bin\chef-solo.bat -v).split(" ", 2)[1] }
    Catch { $chef_version = "" }
  }

  if ($chef_version.StartsWith($version)) { return $false }
  else { return $true }
}

Function Get-ChefMetadata($url) {
  Try { $response = ($c = Make-WebClient).DownloadString($url) }
  Finally { if ($c -ne $null) { $c.Dispose() } }

  $md = ConvertFrom-StringData $response.Replace("`t", "=")
  return @($md.url, $md.md5)
}

Function Get-MD5Sum($src) {
  Try {
    $c = New-Object -TypeName System.Security.Cryptography.MD5CryptoServiceProvider
    $bytes = $c.ComputeHash(($in = (Get-Item $src).OpenRead()))
    return ([System.BitConverter]::ToString($bytes)).Replace("-", "").ToLower()
  } Finally { if (($c -ne $null) -and ($c.GetType().GetMethod("Dispose") -ne $null)) { $c.Dispose() }; if ($in -ne $null) { $in.Dispose() } }
}

Function Download-Chef($md_url, $dst) {
  $url, $md5 = Get-ChefMetadata $md_url

  Try {
    Log "Downloading package from $url"
    ($c = Make-WebClient).DownloadFile($url, $dst)
    Log "Download complete."
  } Finally { if ($c -ne $null) { $c.Dispose() } }

  if (($dmd5 = Get-MD5Sum $dst) -eq $md5) { Log "Successfully verified $dst" }
  else { throw "MD5 for $dst $dmd5 does not match $md5" }
}

Function Install-Chef($msi) {
  Log "Installing Chef Omnibus package $msi"
  $p = Start-Process -FilePath "msiexec.exe" -ArgumentList "/qn /i $msi" -Passthru -Wait

  if ($p.ExitCode -ne 0) { throw "msiexec was not successful. Received exit code $($p.ExitCode)" }

  Remove-Item $msi -Force
  Log "Installation complete"
}

Function Log($m) { Write-Host "       $m`n" }

Function Make-WebClient {
  $proxy = New-Object -TypeName System.Net.WebProxy
  $proxy.Address = $env:http_proxy
  $client = New-Object -TypeName System.Net.WebClient
  $client.Proxy = $proxy
  return $client
}

Function Unresolve-Path($p) {
  if ($p -eq $null) { return $null }
  else { return $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($p) }
}

$chef_omnibus_root = Unresolve-Path $chef_omnibus_root
$msi = Unresolve-Path $msi

if (Check-UpdateChef $chef_omnibus_root $version) {
  Write-Host "-----> Installing Chef Omnibus ($pretty_version)`n"
  Download-Chef "$chef_metadata_url" $msi
  Install-Chef $msi
} else {
  Write-Host "-----> Chef Omnibus installation detected ($pretty_version)`n"
}
]
D      ------Backtrace-------
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/base.rb:74:in `rescue in call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/base.rb:77:in `call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:366:in `block in converge_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `synchronize_or_call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:453:in `block in action'
D      C:/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:452:in `action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:362:in `converge_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:341:in `block in transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `each'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:138:in `converge'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D      ----------------------
D      [CommandExecutor] closing remote shell C116E251-E264-4CE5-8482-3326B11C7674 on plaintext::http://127.0.0.1:5985/wsman<{:disable_sspi=>true, :basic_auth_only=>true, :user=>"vagrant", :pass=>"vagrant"}>
D      [CommandExecutor] remote shell C116E251-E264-4CE5-8482-3326B11C7674 closed
`

**Comment by schisamo** [comment]
After digging into this we will most likely need to release a patch release of the TK `v1.4.x` series (so `v1.4.3`). This is not an issue with Test Kitchen `v1.5`+ which ships in ChefDK `0.11.0`+. The fastests workaround would be to upgrade your ChefDK to the latest (current version is `0.12.0`):
https://downloads.chef.io/chef-dk/

**Comment by mwrock** [comment]
Best thing to do is to update your test-kitchen to 1.6. You can do that by either updating chefdk or if you want to keep the chefdk version you are on, fillow the instructions [here](https://discourse.chef.io/t/updating-to-test-kitchen-1-6-0-in-a-chefdk-0-11-2-or-lesser/7899)
