### ISSUE TITLE
Windows 2012R2 Chef Client MD5 checksum mismatch

### ISSUE THREAD

**Issue by gmreburn** [test-kitchen/test-kitchen#986]
## Description

Converging Windows 2012R2 using test kitchen results in a md5 checksum mismatch for chef client msi. Chef client v12.8.1 is being downloaded from https://packages.chef.io/stable/windows/2012r2/chef-client-12.8.1-1-x86.msi

## Kitchen Version

```ruby
1.4.2
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
0.10.0
```

## Platform Version

Windows 7 64bit

## Replication Case

- Create a basebox with windows server 2012r2 OS
- run `kitchen converge`

## Kitchen Output

[https://gist.github.com/gmreburn/534a7507c3733fcf3dba83f53ff4cf7c](https://gist.github.com/gmreburn/534a7507c3733fcf3dba83f53ff4cf7c)

```ruby
> I, [2016-03-31T11:59:38.473870 #11096]  INFO -- default-windows-2012r2: -----> Installing Chef Omnibus (install only if missing)
> I, [2016-03-31T11:59:39.107370 #11096]  INFO -- default-windows-2012r2: Downloading package from https://packages.chef.io/stable/windows/2012r2/chef-client-12.8.1-1-x86.msi
> I, [2016-03-31T11:59:58.264870 #11096]  INFO -- default-windows-2012r2: Download complete.
> W, [2016-03-31T11:59:58.500370 #11096]  WARN -- default-windows-2012r2: MD5 for C:\Users\vagrant\AppData\Local\Temp\chef-true.msi
> W, [2016-03-31T11:59:58.500870 #11096]  WARN -- default-windows-2012r2: 458177d3b21888c17fd79660781d06eb does not match
```

## Kitchen Diagnose

[https://gist.github.com/gmreburn/d7b795bbe409123049425e004494e9c0](https://gist.github.com/gmreburn/d7b795bbe409123049425e004494e9c0)

**Comment by mwrock** [comment]
This is a known issue on older Test-Kitchen installs. Please see
This is a known issue that has recently shown up on Test-Kitchen 1.4.2 and earlier due to a recent change in how we host the chef client packages. The best way to unblock yourself is to update your Test-Kitchen install to 1.6. See [this discourse post](https://discourse.chef.io/t/test-kitchen-md5-checksum-failures-during-chef-client-install-on-windows/8116) for more details.
